### ISSUE TITLE
File spray fails

### ISSUE THREAD

**Issue by JamesDeFabia** [GordonSmith/ECL-Playground#1]
I uploaded a CSV file and tried to spray it using ECL Watch . 

It failed with this message:

Failed: 10.64.22.22: SSH failed to connect 10.64.22.22: /opt/HPCCSystems/bin/run_ftslave 10.64.22.22 1 0 6407 D20211005-143107 /var/log/HPCCSystems/mydfuserver

**Comment by GordonSmith** [comment]
https://track.hpccsystems.com/browse/HPCC-26683

**Comment by GordonSmith** [comment]
@JamesDeFabia - this is now fixed.
